# Global values for all helm charts. See comments for usage
#
# NOTE: If you update this file beware to not commit/push inside your repo!
# Instead of updating this file, can place a updated copy of it in helm/__values folder and use the -valuesFile parameter of Deploy-Images-Aks.ps1 script.
# Everything on helm/__values folder is ignored by .gitignore.

inf:
  sa: ttsa
  db:
    rewards:
      host: # DB HOST LIKE tailwindtradersserver-dev.database.windows.net
      port: "1433"
      catalog: # DB NAME LIKE  Microsoft.Tailwind.Rewards-dev
      user: # ADMIN USERNAME LIKE tailadmin
      pwd: # ADMIN PWD
  appinsights:
    id: ""
  ingress:
    webrewards:
      path: /rewards
  apiurls:
    webrewardsurl: http://webrewards

# Shared ingress configurations
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /

  tls: []

sec:
  issuer: TTFakeLogin
  securityKey: nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
