version: '3.4'

services:
  sql.data:
      environment:
        - SA_PASSWORD=Pass@word
        - ACCEPT_EULA=Y
      ports:
        - "5433:1433"
      healthcheck:
        test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "Pass@word", "-Q", "select 1" ]
        interval: 1s
        retries: 20

  tailwindtraders.rewards.website:
    environment:
    - ConnectionString=Server=sql.data;Database=rewardsdb;User Id=sa;Password=Pass@word
    - AdminUsername=admin
    - AdminPassword=adm!n%
    ports:
      - "2100:80"

networks:
  default:
    external:
      name: nat
